### PR TITLE
Changes to Django v2

### PR DESCRIPTION
**Pull request by brunoprograma**
In Django v2 User.is_authenticated is just a flag that returns a boolean value. It is not a class method anymore.

### CODE REVIEW

**Comment by brunoprograma** [comment]
@kunaldeo tested with Django 2.2 LTS

**Comment by kunaldeo** [comment]
Thanks for the pull request. Have you tested it with https://github.com/kunaldeo/django-livesettings3?

**Comment by brunoprograma** [comment]
> Thanks for the pull request. Have you tested it with https://github.com/kunaldeo/django-livesettings3?

Yes. It's a minimal change. Doesn't have any negative effects. I'm using both packages in production.

**Comment by kunaldeo** [comment]
Thanks

**Pull request merged**
